---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_paths:
    - tests/
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
